### ISSUE TITLE
updated_memory_cost = 8 in miner.py

### ISSUE THREAD

**Issue by bitcoinholder** [jacklevin74/xenminer#4]
miner.py line 44:

updated_memory_cost = 8 # just initialize it`

It should be 8 * cores if cores and memory_cost are different than default (cores=1, memory_cost=8).

Otherwise the script gives this error:

_Genesis Block: 7d9e89df799138be2e985c80e9dd47fa68bf55a6c74d55e624b28419aea42eee
Mining block 1...
Mining: 90 Hashes [00:00, 1391.94 Hashes/s, Difficulty=16]Continuing to mine blocks with new difficulty
Mining: 99 Hashes [00:00, 1399.68 Hashes/s, Difficulty=16]
Restarting mining round
Mining block 1...
Traceback (most recent call last):
  File "/root/xenminer/miner.py", line 187, in <module>
    result = mine_block(target_substr, blockchain[-1]['hash'])
  File "/root/xenminer/miner.py", line 88, in mine_block
    argon2_hasher = argon2.using(time_cost=difficulty, salt=b"XEN10082022XEN", memory_cost=memory_cost, parallelism=cores, hash_len = 64)
  File "/usr/local/lib/python3.10/dist-packages/passlib/handlers/argon2.py", line 309, in using
    subcls._validate_constraints(subcls.memory_cost, subcls.parallelism)
  File "/usr/local/lib/python3.10/dist-packages/passlib/handlers/argon2.py", line 328, in _validate_constraints
    raise ValueError("%s: memory_cost (%d) is too low, must be at least "
ValueError: argon2: memory_cost (8) is too low, must be at least 8 * parallelism (8 * 2 = 16)_

this error occured when:

_memory_cost = 16
cores = 2_

**Comment by bitcoinholder** [comment]
Resolved
